#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: rootroot
#
#  #JPA Settings
#  jpa.hibernate.ddl_auto: update
#  jpa.show-sql: true